name: ccxt_env
dependencies:
  - python=3.6.0
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip:
    - ccxt
    - mpld3
    - jinja2
    - ipykernel  #  to make the environment show up in jupyter notebook. execute: python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
    - openpyxl
